runtime: python39
service: chat-api

instance_class: F2
entrypoint: gunicorn main:app -b :$PORT -w 2 -k uvicorn.workers.UvicornWorker --timeout 60

automatic_scaling:
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7
  max_concurrent_requests: 25
  max_instances: 1

handlers:
  - url: /static/v1/static/
    static_dir: static/

  - url: /.*
    script: auto

inbound_services:
- warmup
