# Generated by Django 4.1.9 on 2024-08-15 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_count", models.IntegerField(default=0)),
                (
                    "followup_check_executed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("requires_followup", models.BooleanField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("accepted", "accepted")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=48,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("message_text", models.TextField(null=True)),
                ("content", models.JSONField(null=True)),
                ("tool_calls", models.JSONField(null=True)),
                ("tool_call_id", models.CharField(max_length=128, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="chat_api.conversation",
                    ),
                ),
            ],
        ),
    ]
