# Generated by Django 4.1.9 on 2024-08-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0002_conversation_alter_userinvitation_status_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="followup_check_executed_at",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="reminder_count",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="requires_followup",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="summary",
        ),
    ]
