# Generated by Django 4.1.9 on 2024-08-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0003_remove_conversation_followup_check_executed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attending", models.BooleanField()),
                ("days_attending", models.IntegerField(blank=True, null=True)),
                ("guest_number", models.IntegerField()),
                ("guest_names", models.JSONField()),
                ("needs_accommodation_help", models.BooleanField()),
                ("food_preference", models.CharField(max_length=255)),
                ("interested_in_top_of_babia_gora", models.BooleanField()),
                ("not_attending_reason", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
