# Generated by Django 4.1.9 on 2024-08-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0004_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="attending",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="food_preference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="guest_names",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="guest_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="interested_in_top_of_babia_gora",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="needs_accommodation_help",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="preference",
            name="not_attending_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
