# Generated by Django 4.1.9 on 2024-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0005_alter_preference_attending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="preferences_gathered",
            field=models.BooleanField(default=False),
        ),
    ]
