# Generated by Django 4.1.9 on 2024-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0006_conversation_preferences_gathered"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="interested_in_triathlon_games",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
