# Generated by Django 4.1.9 on 2024-08-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_api", "0007_preference_interested_in_triathlon_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="preference",
            name="has_ideas",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preference",
            name="ideas",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
