# Generated by Django 5.1.1 on 2024-11-29 05:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("board_state", models.TextField()),
                (
                    "moves",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), size=None
                    ),
                ),
                ("game_status", models.CharField(max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
