# Generated by Django 5.1.1 on 2024-11-29 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="moves",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
