# Generated by Django 5.1.1 on 2024-11-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_api", "0002_alter_chessgame_moves"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="current_player",
            field=models.CharField(
                blank=True, default="white", max_length=256, null=True
            ),
        ),
    ]
