# Generated by Django 5.1.1 on 2024-12-07 10:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_api", "0004_chessgame_human_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chessgame",
            name="board_state",
            field=models.TextField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
            ),
        ),
        migrations.AlterField(
            model_name="chessgame",
            name="moves",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                default=[],
                null=True,
                size=None,
            ),
        ),
    ]
